### ISSUE TITLE
Use "use" in ext_localconf.php for TYPO3 V10

### ISSUE THREAD

**Issue by AlenBilalovic** [nitsan-technologies/ns_personio#3] opened 2023-12-07 09:26 UTC
Hello,

We just had an issue with TYPO3 V10 in regard to usage of "use" statement in ext_localconf.php.

`Fatal error: Cannot use TYPO3\CMS\Core\Utility\GeneralUtility
as GeneralUtility because the name is already in use
in /var/www/site/public/typo3temp/var/cache/code/cache_core/ext_localconf_feb178af00fe22e00dc62d7dcd6d4d16f5d4fc3a.php
on line 3419`

That option is available in v11 and after, so it seems.
https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ExtensionArchitecture/BestPractises/ConfigurationFiles.html#id2

All the use statements have to be removed and referenced directly where needed.

If any additional feedback needed, just let me know.

Thanks in advance.

Best Regards
Alen

**Comment by nitsan-technologies** [comment] 2023-12-08 06:08
Hey Alen,

Thank you for providing feedback, and we apologize for any inconvenience.

Upon investigation, we found that the issue is not consistent, but it does occur at times. Clearing the cache has proven effective in resolving it.

Our team is committed to enhancing the TYPO3 v10 code. As a best practice for v10, it is advisable to use the full namespace in the ext_tables and ext_localconf files.

For further details, refer to:
https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ExtensionArchitecture/BestPractises/ConfigurationFiles.html#id2

![image](https://github.com/nitsan-technologies/ns_personio/assets/2622317/7bfd15f6-9137-4d8d-b8ff-3ca2b74ccab1)

Due to the existing workload, we are unable to address this immediately but plan to allocate time to resolve the issue in the coming weeks.

We appreciate your understanding and support.

Cheers, Team NITSAN

**Comment by nitsan-technologies** [comment] 2024-06-13 11:48
Hey Alen,

We have fix the issue with TYPO3 V10 in regard to usage of "use" statement in ext_localconf.php in stable version of 1.1.0.

Cheers, Team NITSAN

**Closed as completed** 2024-06-13 11:48 UTC
